### PyTorch Tutorial 60 minutes blitz - Basics of PyTorch

In [2]:
from __future__ import print_function
import torch
import torchvision
from torchvision import datasets,transforms


#### basic stuff

In [3]:
x = torch.empty(5,3)

In [9]:
print(x) #whatever values were there at mem loc before allocation

tensor([[1.1307e-21, 4.5681e-41, 1.6056e+27],
        [3.0931e-41,        nan, 3.0931e-41],
        [4.6083e-39, 3.0931e-41, 1.5887e+27],
        [3.0931e-41, 2.0319e-43, 0.0000e+00],
        [1.6326e+27, 3.0931e-41, 1.6640e+27]])


In [10]:
x = torch.rand(5,3)

In [11]:
print(x)

tensor([[0.0755, 0.1984, 0.7212],
        [0.6720, 0.0222, 0.0584],
        [0.4364, 0.3218, 0.7280],
        [0.1343, 0.5469, 0.8850],
        [0.9704, 0.9832, 0.6276]])


In [13]:
x = torch.zeros(5,3, dtype=torch.long)

In [14]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
x = torch.tensor([5,3])

In [16]:
print(x)

tensor([5, 3])


In [17]:
x = torch.ones(5,3)

In [31]:
list(x.size())  # x.size is a tuple and support all tuple operations

[5, 3]

In [30]:
#create a tensor based on existing tensor new_* but it takes sizes
y = x.new_zeros(size=x.size())

In [22]:
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
z = torch.randn_like(x,dtype=torch.float)

In [24]:
z

tensor([[ 0.6841, -0.8358, -0.3119],
        [ 0.8362, -0.0598,  1.2301],
        [ 0.8889,  1.9005,  1.2464],
        [ 0.4770,  0.1764,  0.1853],
        [ 1.0269,  1.8007,  0.6005]])

In [32]:
#operations
z+y

tensor([[ 0.6841, -0.8358, -0.3119],
        [ 0.8362, -0.0598,  1.2301],
        [ 0.8889,  1.9005,  1.2464],
        [ 0.4770,  0.1764,  0.1853],
        [ 1.0269,  1.8007,  0.6005]])

In [34]:
p = torch.empty(5,3)
torch.add(z,y,out=p)

tensor([[ 0.6841, -0.8358, -0.3119],
        [ 0.8362, -0.0598,  1.2301],
        [ 0.8889,  1.9005,  1.2464],
        [ 0.4770,  0.1764,  0.1853],
        [ 1.0269,  1.8007,  0.6005]])

In [35]:
p

tensor([[ 0.6841, -0.8358, -0.3119],
        [ 0.8362, -0.0598,  1.2301],
        [ 0.8889,  1.9005,  1.2464],
        [ 0.4770,  0.1764,  0.1853],
        [ 1.0269,  1.8007,  0.6005]])

In [36]:
#inplace additions 
p.add_(x)

tensor([[1.6841, 0.1642, 0.6881],
        [1.8362, 0.9402, 2.2301],
        [1.8889, 2.9005, 2.2464],
        [1.4770, 1.1764, 1.1853],
        [2.0269, 2.8007, 1.6005]])

In [38]:
p[:,:1]  #indexing runs like numpy

tensor([[1.6841],
        [1.8362],
        [1.8889],
        [1.4770],
        [2.0269]])

#### resizing

In [98]:
p.size()

torch.Size([5, 3])

In [99]:
r = p.view(-1,5)   # -1 is inferred from other dimension   ie. (_,columns)

In [44]:
r

tensor([[1.6841, 0.1642, 0.6881, 1.8362, 0.9402],
        [2.2301, 1.8889, 2.9005, 2.2464, 1.4770],
        [1.1764, 1.1853, 2.0269, 2.8007, 1.6005]])

In [45]:
f = r.view(5*3)

In [53]:
f

tensor([1.6841, 0.1642, 0.6881, 1.8362, 0.9402, 2.2301, 1.8889, 2.9005, 2.2464,
        1.4770, 1.1764, 1.1853, 2.0269, 2.8007, 1.6005])

In [102]:
### lets try 3d matrix 
img = torch.empty(2,5,3)   ##depth = 2, rows=2 col=3

In [103]:
img

tensor([[[4.6840e-310, 9.5849e-322,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, 5.0203e+175],
         [ 1.3958e-47,  3.5654e-57,  1.7724e-51],
         [3.9543e+179, 1.4776e+248,  1.1610e-28],
         [7.6917e+218, 1.3562e+248,  9.5690e-71]],

        [[ 1.8158e-52,  8.9751e-67,  2.6107e-57],
         [ 4.3026e-96, 6.3230e+233, 6.4822e+170],
         [5.2241e+257, 5.7402e+180, 8.3717e-144],
         [1.4153e+161,  6.0074e-67,  4.3138e+97],
         [ 7.2766e-43, 2.9127e+126, 5.4324e-312]]])

In [108]:
flat_img = img.view(2*5*3) ###flattened

In [110]:
flat_img.size()

torch.Size([30])

#### others

In [52]:
f[1].item()   #to get number as python number out not as tensor dtype

0.16416329145431519

In [54]:
torch.is_floating_point(f)

True

In [57]:
torch.set_default_dtype(torch.float64)

In [58]:
torch.get_default_dtype()

torch.float64

In [60]:
#no of elements in tensor 
torch.numel(f)

15

#### convert to numpy

In [94]:
f.numpy()

array([1.6841403 , 0.16416329, 0.68811744, 1.8362285 , 0.94019455,
       2.230063  , 1.8889054 , 2.9004812 , 2.2464027 , 1.4769645 ,
       1.1764094 , 1.1852916 , 2.0269074 , 2.8006654 , 1.6005466 ],
      dtype=float32)

#### from numpy

In [97]:
b = torch.from_numpy(f.numpy())
b

tensor([1.6841, 0.1642, 0.6881, 1.8362, 0.9402, 2.2301, 1.8889, 2.9005, 2.2464,
        1.4770, 1.1764, 1.1853, 2.0269, 2.8007, 1.6005], dtype=torch.float32)

#### sampling from distrbutions

In [62]:
x = torch.randperm(5)  #random permutation from 0 to n-1

In [63]:
x

tensor([3, 2, 1, 0, 4])

In [78]:
#uniform 
u = torch.empty(3,3).uniform_(0,1) #inplace and drawn every element from uniform distribution from 0 to 1

In [66]:
u

tensor([[0.7033, 0.9324, 0.5951],
        [0.6628, 0.2446, 0.9312],
        [0.1809, 0.1719, 0.5831]])

#### bernoulli 
Draws binary random numbers (0 or 1) from a Bernoulli distribution.

The input tensor should be a tensor containing probabilities to be used for drawing the binary random number. Hence, all values in input have to be in the range: 0 \leq \text{input}_i \leq 10≤input 
i


In [68]:
ber = torch.bernoulli(u)   ##every element ber[i][j] is drawn with probability u[i][j]

In [69]:
ber

tensor([[0., 1., 0.],
        [1., 0., 1.],
        [0., 0., 0.]])

 #### normal


In [77]:
 torch.normal(mean=torch.arange(1.,3.), std=torch.arange(1, 1.2,0.1))

tensor([4.1435, 1.2832])

In [80]:
torch.empty(4,5).normal_()   # mean =0 and std = 1 common for all 

tensor([[ 0.9200, -0.2689, -0.2903, -0.2738, -2.3488],
        [ 0.9162,  1.5318, -1.2294, -0.9844,  0.2938],
        [ 0.0406,  1.1669,  0.3260, -0.7826,  0.3797],
        [ 0.6635,  0.0212,  0.5828,  0.6645,  0.4748]])

#### norm


In [88]:
f

tensor([1.6841, 0.1642, 0.6881, 1.8362, 0.9402, 2.2301, 1.8889, 2.9005, 2.2464,
        1.4770, 1.1764, 1.1853, 2.0269, 2.8007, 1.6005], dtype=torch.float32)

In [89]:
f.size()

torch.Size([15])

In [93]:
torch.norm(f).item() ###gives l2 norm for vector and frob for matrix. other options  'nuc' norm

7.005486965179443

### cuda tensors

In [111]:
torch.cuda.is_available()

True

In [113]:
##always write it within if
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.rand(5,3,device=device)
    z = torch.rand(5,3,device=device)
    cuda_add = y+z
    print(cuda_add)

tensor([[1.7165, 1.4663, 0.9889],
        [1.2787, 0.9946, 0.4919],
        [1.1751, 0.8589, 0.7639],
        [1.4035, 1.0794, 0.7931],
        [1.1938, 0.4823, 0.6409]], device='cuda:0')


In [114]:
cuda_add

tensor([[1.7165, 1.4663, 0.9889],
        [1.2787, 0.9946, 0.4919],
        [1.1751, 0.8589, 0.7639],
        [1.4035, 1.0794, 0.7931],
        [1.1938, 0.4823, 0.6409]], device='cuda:0')

In [117]:
p=cuda_add.to("cpu")

In [118]:
cuda_add

tensor([[1.7165, 1.4663, 0.9889],
        [1.2787, 0.9946, 0.4919],
        [1.1751, 0.8589, 0.7639],
        [1.4035, 1.0794, 0.7931],
        [1.1938, 0.4823, 0.6409]], device='cuda:0')

In [119]:
p

tensor([[1.7165, 1.4663, 0.9889],
        [1.2787, 0.9946, 0.4919],
        [1.1751, 0.8589, 0.7639],
        [1.4035, 1.0794, 0.7931],
        [1.1938, 0.4823, 0.6409]])